version: '3.1'

services:
  nginx:
    image: nginx
    container_name: project_name_nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/static
      - ./media:/media
      - ./nginx/project_name.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - project_name

  project_name:
    build: .
    image: project_name:latest
    container_name: project_name
    environment:
      ENVIRONMENT: 
      PAYPAL_SECRENT_CLIENT:
    depends_on:
      - db
    volumes:
      - .:/src
      - ./scripts:/scripts
    # Dev user: admin pass: admin
    command: ["/scripts/wait-for-it.sh", "db:5432", "--", "/scripts/command-dev.sh"]
    ports:
      - "8000:8000"

  db:
    image: postgres:11
    container_name: project_name-postgres
    environment: 
      POSTGRES_PASSWORD: postgres
